const C=[
{key:'france',name:'Франция',code:'fr',region:'Европа',domain:'.fr',drive:'справа',language:'Французский: rue, mairie, sortie, école, chemin; é è ê à ç. В названиях много -eux/-eau/-ville.',plates:'Белые номера, обычно синяя EU-полоса слева; современный формат визуально обычный европейский.',roads:'Часто длинные штрихи центра/края; встречаются характерные offset-block линии. Асфальт очень разный — цвет слабый clue.',roadside:'Белые французские болларды с тёмной вставкой; ladder poles; на столбах/опорах может быть синяя наклейка.',architecture:'Очень региональная: светлая штукатурка и черепица на юге, камень на западе, кирпич севернее. Деревни часто плотные, дома близко к дороге.',urban:'Города не обязательно высотные; типичны 3–6 этажей, ставни, каменные фасады. Парижская застройка не代表 всей страны.',religion:'Католические церкви/шпили чаще мечетей. Мечеть сама по себе Францию не исключает, но не country clue.',hydrant:'Не используй цвет гидранта как Францию — нет надёжной общенациональной GeoGuessr-меты.',landscape:'От очень плоского севера до Альп и Средиземноморья.',meta:'Слова RUE / MAIRIE, французские дорожные номера и инфраструктура сильнее архитектуры.',confuse:'Германия, Бельгия, Швейцария, Люксембург.',last:'France vs Germany: сначала язык. Rue/sortie/école → Франция; Straße/Ausfahrt/ß → Германия. Если текста нет — сравни болларды и столбы.'},
{key:'germany',name:'Германия',code:'de',region:'Европа',domain:'.de',drive:'справа',language:'Немецкий: Straße/Str., Ausfahrt, Einbahnstraße, Gemeinde, Bahnhof; ß, ä, ö, ü. Часто длинные составные слова.',plates:'Белые EU-номера; по blur обычно ничем супер-уникальным не выделяются.',roads:'Очень аккуратная разметка, дороги часто качественные. Но качество дороги само по себе не доказательство.',roadside:'Немецкие болларды: белые с крупной чёрной прямоугольной панелью; один из лучших визуальных clues Германии.',architecture:'Скатные крыши, штукатурка, кирпич на севере, фахверк локально. Много аккуратных частных домов и деревень.',urban:'Средняя этажность; крупные города современнее. Высотки встречаются, но не как Dubai-style skyline.',religion:'Церкви обычны; мечети возможны в крупных городах, но не clue.',hydrant:'Наземные и подземные системы разные; цвет отдельного гидранта не учи как country clue.',landscape:'Север плоский, юг холмистый/Альпы.',meta:'Bollard + немецкий текст — очень надёжная комбинация.',confuse:'Франция, Австрия, Швейцария, Нидерланды.',last:'Germany vs Netherlands: Нидерланды почти всегда выдают жёлтые номера и очень плоский ландшафт; Германия — белые номера + немецкий.'},
{key:'netherlands',name:'Нидерланды',code:'nl',region:'Европа',domain:'.nl',drive:'справа',language:'Нидерландский: straat, weg, gemeente, centrum, ingang/uitgang; ij, aa, ee, oo, ui. Похож на немецкий/английский, но без ß.',plates:'ЯРКО-ЖЁЛТЫЕ номера спереди и сзади — один из сильнейших clues.',roads:'Очень много велоинфраструктуры, красный/розовый велоасфальт; дороги и каналы часто идут параллельно.',roadside:'Аккуратные канавы, дамбы, мостики, велосипедные знаки.',architecture:'Кирпичные дома, большие окна, плотные ряды домов; фермерские районы очень ухожены.',urban:'Плотные низко-/среднеэтажные города, много велосипедов. В Роттердаме/Гааге бывают высотки.',religion:'Не полезно.',hydrant:'Не основной clue.',landscape:'Экстремально плоско; вода/каналы постоянно.',meta:'Жёлтые номера + плоско + велосипеды/каналы = почти закрытый раунд.',confuse:'Германия, Бельгия, Дания.',last:'Если думаешь Германия или Нидерланды: сначала номера. Жёлтые с обеих сторон → NL.'},
{key:'belgium',name:'Бельгия',code:'be',region:'Европа',domain:'.be',drive:'справа',language:'Север — нидерландский, юг — французский. Поэтому язык может выглядеть как NL или France.',plates:'Номера часто дают красноватый/бордовый текст на светлом фоне — через blur может быть лёгкий красный оттенок.',roads:'Бетонные плиты встречаются заметно чаще, чем в соседних странах; локально двойные канавки/водоотвод.',roadside:'Жёлтые reflectors на guardrail возможны; квадратные столбы и маленькие priority signs.',architecture:'Очень плотная ленточная застройка вдоль дорог, кирпич, индивидуальные дома почти без разрыва между городами.',urban:'Может ощущаться как смесь Франции и Нидерландов.',religion:'Не основной clue.',hydrant:'Не основной clue.',landscape:'Фландрия плоская, Валлония холмистее.',meta:'Розово-красный номер + смешение NL/FR языка — сильная Бельгия.',confuse:'Франция, Нидерланды, Люксембург.',last:'Если язык французский, но дороги/дома очень «нидерландские», проверь Бельгию.'},
{key:'luxembourg',name:'Люксембург',code:'lu',region:'Европа',domain:'.lu',drive:'справа',language:'Люксембургский + французский + немецкий. На одном раунде можно увидеть смесь языков.',plates:'Жёлтые номера — важный clue в Европе.',roads:'Очень ухоженные дороги, леса, холмы.',roadside:'Инфраструктура выглядит западноевропейски, без одного супер-уникального столба.',architecture:'Аккуратные богатые дома, часто светлая штукатурка.',urban:'Небольшие города/посёлки, очень ухоженно.',religion:'Не основной clue.',hydrant:'Не основной clue.',landscape:'Холмистее Нидерландов, много леса.',meta:'Жёлтый номер + не плоско + смесь FR/DE = думай Luxembourg.',confuse:'Нидерланды, Бельгия, Германия, Франция.',last:'NL vs Luxembourg: оба могут иметь жёлтые номера; NL заметно площе, больше каналов/велодорог.'},
{key:'slovakia',name:'Словакия',code:'sk',region:'Европа',domain:'.sk',drive:'справа',language:'Словацкий: ľ, ĺ, ŕ, ô, ä; слова obec, cesta, námestie, Slovensko. Похож на чешский, но специальные ľ/ô/ĺ сильны.',plates:'Обычные белые EU-номера.',roads:'Синие directional signs; часто крупный жирный шрифт на дорожных знаках.',roadside:'Словацкие болларды; pair poles; wooden poles; встречаются special B-type guardrails.',architecture:'Скатные крыши, штукатурка, сельские дома; серые металлические крыши встречаются часто.',urban:'Небольшие города и посёлки; панельные районы есть.',religion:'Католические церкви довольно часты.',hydrant:'Не основной clue.',landscape:'Либо очень плоский юг, либо резко горная/холмистая северная часть.',meta:'Большой жирный шрифт знаков + словацкие буквы + горы/долины.',confuse:'Чехия, Словения, Хорватия, Польша.',last:'Slovakia vs Croatia: словацкий чаще имеет Ľ/Ô/Ä/Ŕ/Ĺ; хорватский — ć/đ и слово Hrvatska. У Хорватии также синие пожарные гидранты и краснокирпичная архитектура встречаются как мета.'},
{key:'croatia',name:'Хорватия',code:'hr',region:'Европа',domain:'.hr',drive:'справа',language:'Хорватский: č ć đ š ž; ulica, cesta, općina, Hrvatska. В отличие от словацкого нет типичных ľ/ô/ĺ.',plates:'Белые EU-номера.',roads:'B-type guardrails встречаются; побережье часто узкие извилистые дороги на карсте.',roadside:'Хорватские болларды; Gen3 mirror встречается в старом coverage.',architecture:'Очень полезно: красный кирпич и незавершённые кирпичные дома внутри страны; на Адриатике — светлый камень, красная черепица.',urban:'Загреб — центральноевропейский; побережье — средиземноморское.',religion:'Католические церкви. На побережье каменные колокольни.',hydrant:'СИНИЕ пожарные гидранты — известный хорватский clue. Не каждый гидрант будет синим, но если увидел характерный синий — это реально полезно.',landscape:'Континентальная зелень на севере/востоке, карст и горы у Адриатики.',meta:'Blue fire hydrant + Croatian language + red brick = сильная связка.',confuse:'Словения, Сербия, Словакия, Черногория.',last:'Croatia vs Slovakia: домен .hr vs .sk; язык ć/đ/Hrvatska vs ľ/ô/Slovensko; синий гидрант толкает в Хорватию.'},
{key:'slovenia',name:'Словения',code:'si',region:'Европа',domain:'.si',drive:'справа',language:'Словенский: č š ž; cesta, ulica, občina, Slovenije. Без хорватской ć/đ.',plates:'Белые EU-номера.',roads:'Жёлтые directional signs — полезное отличие от Австрии; длинные dashed outlines.',roadside:'Похожие на Австрию болларды; A-type guardrails.',architecture:'Альпийская/центральноевропейская, аккуратные дома со скатными крышами.',urban:'Небольшие чистые города, много зелени.',religion:'Католические церкви.',hydrant:'Не основной clue.',landscape:'Очень лесистая и холмистая; Альпы на северо-западе.',meta:'Очень много леса + словенский + австрийский вайб.',confuse:'Австрия, Хорватия, Словакия.',last:'Slovenia vs Croatia: Словения обычно более альпийская/лесистая и аккуратная; Хорватия чаще карст/красный кирпич/побережье.'},
{key:'czechia',name:'Чехия',code:'cz',region:'Европа',domain:'.cz',drive:'справа',language:'Чешский: ř, ě, ů; náměstí, obec. Буква ř — почти подарок.',plates:'Белые EU-номера.',roads:'Directional signs отличаются от словацких; иногда дороги без centerline на меньших трассах.',roadside:'Чешские болларды; black sign caps, pair poles.',architecture:'Плотные деревни, штукатурка, скатные крыши; pair houses встречаются.',urban:'Исторические центры + панельные окраины.',religion:'Церкви обычны.',hydrant:'Не основной clue.',landscape:'Чаще rolling hills, менее экстремально горно, чем Словакия.',meta:'ř/ě/ů + чешские bolllards.',confuse:'Словакия, Польша, Австрия.',last:'Czechia vs Slovakia: ř/ě/ů → CZ; ľ/ô/ĺ → SK. Словакия чаще даёт более крупный жирный дорожный шрифт.'},
{key:'turkey',name:'Турция',code:'tr',region:'Ближний Восток',domain:'.tr',drive:'справа',language:'ТУРЕЦКИЙ — латиница: ğ, ş, ı, İ, ç, ö, ü; cadde/caddesi, sokak, belediyesi. Это главный способ не спутать с арабскими странами.',plates:'Белые длинные номера; формат обычно 2 цифры провинции + буквы/цифры, но читать через blur редко нужно.',roads:'Характерный «salt & pepper» асфальт встречается; белая разметка. Chevrons могут быть black-on-yellow / yellow-on-black.',roadside:'Турецкие болларды похожи на Австралию, но без заднего reflector. Разные водяные баки на крышах — вертикальные, горизонтальные, квадратные, сферические по регионам.',architecture:'Очень много 4–10 этажных бетонных apartment blocks; на юге flat roofs, на западе черепица, в центре/востоке более сухая застройка.',urban:'Стамбул/Анкара/Измир — плотные многоэтажные кварталы; не Dubai-style сверхсовременные башни повсюду.',religion:'Мечети с тонкими высокими минаретами очень часты. Но мечеть ≠ автоматически Турция.',hydrant:'Не основной clue.',landscape:'Огромное разнообразие: сухое плато, средиземноморье, горы, чайные зелёные районы Чёрного моря.',meta:'Турецкие буквы + мечеть + apartment blocks/водяные баки = очень сильная Турция.',confuse:'ОАЭ, Иордания, Греция, Болгария.',last:'Turkey vs Dubai/UAE: Турция пишет латиницей с ğ/ş/ı; ОАЭ — арабский + английский. Dubai заметно более современный, шире магистрали, светлый камень, пустыня, высокие башни.'},
{key:'uae',name:'ОАЭ / Dubai',code:'ae',region:'Ближний Восток',domain:'.ae',drive:'справа',language:'Арабский + очень много английского на тех же знаках. Домен .ae. Если видишь Dubai, Abu Dhabi, Sharjah — очевидно.',plates:'Белые номера разных эмиратов, часто компактные/с цветными областями; издалека важнее сама современная дорожная среда.',roads:'Широкие многополосные шоссе, очень чёткая разметка, крупные overhead signs. Curbs и reddish sidewalks встречаются как meta.',roadside:'Современные фонари, мощная городская инфраструктура; пустынные обочины вне городов.',architecture:'Светлый камень/штукатурка; виллы за высокими стенами; в Dubai/Abu Dhabi много стеклянных высоток и сверхсовременной застройки.',urban:'Высотки — сильный clue только в сочетании с пустыней + Arabic/English + Gulf инфраструктурой.',religion:'Мечети часты; часто белые/бежевые, с минаретами. Но в Турции мечетей тоже полно — язык решает.',hydrant:'Цвет гидранта не используй как country clue.',landscape:'Почти плоская пустыня, песок/гравий; горы на востоке страны.',meta:'Silver/black car metas в coverage + Arabic/English + роскошная инфраструктура.',confuse:'Катар, Иордания, Турция, иногда Израиль.',last:'UAE vs Turkey: Arabic+English vs Turkish Latin. UAE гораздо чаще даёт пустынную сверхширокую дорожную инфраструктуру и light-colored stone.'},
{key:'iran',name:'Иран',code:'ir',region:'Ближний Восток',domain:'.ir',drive:'справа',language:'Персидский записывается арабской графикой справа налево. На вывесках может быть английский, но основной текст выглядит арабским.',plates:'Иранские номера визуально светлые, с цветной зоной/полосой; в обычном раунде лучше не пытаться читать.',roads:'Правостороннее движение, сухие широкие дороги, горные трассы.',roadside:'Городская инфраструктура ближневосточная; отдельные clues зависят от карты/coverage.',architecture:'Светлый кирпич/камень, плотные кварталы, flat roofs в сухих районах; Тегеран может быть многоэтажным.',urban:'Большие города очень плотные; меньше Gulf-glass-skyscraper эффекта, чем Dubai.',religion:'Мечети и шиитская религиозная архитектура распространены.',hydrant:'Не основной clue.',landscape:'Сухое высокое плато + очень большие горные цепи.',meta:'Главное против Индии: правостороннее движение + Persian/Arabic script. India — левосторонняя и часто English + индийские письменности.',confuse:'Индия (если текст неясен), Иордания, Турция, арабские страны.',last:'Iran vs India: движение — Iran справа, India слева. Письменность — Iran персидско-арабская; India часто Devanagari/другие индийские скрипты + английский. Домен .ir vs .in.'},
{key:'india',name:'Индия',code:'in',region:'Азия',domain:'.in',drive:'СЛЕВА',language:'Очень много английского + региональные письменности: देवनागरी, தமிழ், తెలుగు, ಕನ್ನಡ, മലയാളം, বাংলা и др. Это не один «индийский язык».',plates:'Обычно белые номера у частных машин; коммерческие могут иметь другие схемы. Формат и цвет менее полезны, чем движение/язык.',roads:'От бетонных плит до очень пыльного асфальта. Качество сильно меняется; дорожный материал — слабый clue.',roadside:'Полосатые signposts встречаются; огромное разнообразие столбов по штатам.',architecture:'Плотная хаотичная застройка, бетон/кирпич, плоские крыши, магазины на первых этажах; сельская Индия совсем другая.',urban:'Много мотоциклов, авторикш, автобусов, вывесок на английском + местном языке. Высотки есть в крупных городах.',religion:'Индуистские храмы, мечети, сикхские гурдвары, церкви — зависит от региона. Мечеть не исключает Индию.',hydrant:'Не основной clue.',landscape:'От тропиков до пустынь и Гималаев.',meta:'Low-quality/third-party coverage исторически встречался, но coverage меняется — не ставь это выше движения и языка.',confuse:'Бангладеш, Шри-Ланка, Иран на специальных картах.',last:'India vs Iran: первое — сторона движения. India слева. Второе — скрипт: индийские письменности часто имеют верхнюю линию/округлые формы; Iran — арабская вязь.'},
{key:'japan',name:'Япония',code:'jp',region:'Азия',domain:'.jp',drive:'СЛЕВА',language:'Японский = кандзи + хирагана/катакана: 日本 の です ア. Если сложные иероглифы смешаны с простыми кривыми символами — Japan.',plates:'Белые/зелёные и региональные вариации; номера компактнее европейских.',roads:'Много белой разметки, стрелок/символов на асфальте; узкие дороги даже в плотных районах.',roadside:'Низкая камера; множество проводов; зеркала на перекрёстках; специфичные болларды.',architecture:'Низкие 2–3 этажные дома, черепичные/металлические крыши, очень плотная застройка; современные города при этом могут быть высотными.',urban:'Автоматы, плотная реклама, ж/д инфраструктура, много проводов.',religion:'Храмы/тории возможны, но не гарантированы.',hydrant:'Пожарные обозначения существуют, но не учи цвет гидранта как основной clue.',landscape:'Горы покрывают огромную часть страны.',meta:'Low cam + Japanese script + left drive.',confuse:'Корея, Тайвань.',last:'Japan vs Korea: японский смешивает кандзи с の/し/て; корейский состоит из квадратных блоков с кружками.'},
{key:'southkorea',name:'Южная Корея',code:'kr',region:'Азия',domain:'.kr',drive:'справа',language:'Корейский Hangul: 한 국 서 울 — квадратные блоки из простых линий и кружков.',plates:'Светлые номера; не самый сильный beginner clue.',roads:'Очень развитая дорожная инфраструктура, зелёные/синие directional signs.',roadside:'Характерная чёрно-жёлтая маркировка на нижней/средней части столбов; в отличие от Тайваня полосатая часть обычно не идёт до земли.',architecture:'Много высотных одинаковых apartment complexes даже в небольших городах; плотная современная застройка.',urban:'Города часто буквально окружены горами; много многоэтажек.',religion:'Церкви с неоновыми крестами встречаются заметно часто.',hydrant:'Не основной clue.',landscape:'Очень гористая и зелёная.',meta:'Hangul практически закрывает страну.',confuse:'Япония, Тайвань.',last:'Если видишь много одинаковых высоких жилых башен + Hangul + горы → Korea.'},
{key:'taiwan',name:'Тайвань',code:'tw',region:'Азия',domain:'.tw',drive:'справа',language:'Традиционные китайские иероглифы; латиница встречается на больших указателях.',plates:'Светлые номера.',roads:'Скутеры, плотная разметка, тропическая городская среда.',roadside:'Очень сильный clue: чёрно-жёлтая/оранжевая диагональная маркировка на столбах часто тянется ДО САМОЙ ЗЕМЛИ.',architecture:'Старые бетонные 3–6 этажные здания, металлические навесы, вывески, плитка на фасадах; север может выглядеть серо/влажно.',urban:'Скутеров огромное количество; плотные mixed-use дома.',religion:'Китайские храмы яркие и декоративные.',hydrant:'Не основной clue.',landscape:'Зелёные очень крутые горы рядом с городами.',meta:'Pole marking to ground + traditional Chinese + scooters.',confuse:'Япония, Южная Корея, Гонконг.',last:'Taiwan vs Korea: script решает; Taiwan — китайские иероглифы, Korea — Hangul. Полосатые столбы Taiwan часто окрашены до земли.'},
{key:'malaysia',name:'Малайзия',code:'my',region:'Азия',domain:'.my',drive:'СЛЕВА',language:'Малайский на латинице: jalan = улица/дорога, selamat, bandar. Английский распространён.',plates:'ЧЁРНЫЕ номера с белыми символами; через blur часто воспринимаются как 2 светлых блока.',roads:'Хорошие дороги, белая разметка; тропики.',roadside:'Black-white curbs встречаются; дорожные знаки часто похожи на британскую традицию.',architecture:'Тропические дома, плитка/бетон, коммерческие shophouses; Куала-Лумпур очень высотный.',urban:'Мотоциклы, пальмы, мечети и современные здания.',religion:'Мечети очень часты; купола и минареты. Это полезно вместе с Malay + left drive.',hydrant:'Не основной clue.',landscape:'Влажные тропики, пальмовые плантации, холмы.',meta:'Black plates + left drive + JALAN + тропики.',confuse:'Индонезия, Сингапур, Таиланд.',last:'Malaysia vs Indonesia: обе малайские языки; Malaysia движется слева и чёрные номера часто дают 2 blur-кластера, Indonesia — тоже слева, но чаще 3 кластера и среда беднее/хаотичнее.'},
{key:'indonesia',name:'Индонезия',code:'id',region:'Азия',domain:'.id',drive:'СЛЕВА',language:'Индонезийский латиницей: jalan, desa, kabupaten, kecamatan. Очень похож на Malay.',plates:'ЧЁРНЫЕ номера с белыми символами; через blur часто 3 светлых кластера.',roads:'Много узких дорог, мотоциклов, локально бетон/плохой асфальт.',roadside:'Столбы и провода часто хаотичнее, чем в Малайзии.',architecture:'Черепичные крыши, открытые фасады, мечети, плотные деревни; Bali сильно отличается индуистской архитектурой.',urban:'Много мотоциклов, рынков, вывесок.',religion:'Мечети чрезвычайно часты почти везде кроме некоторых регионов; на Bali — индуистские храмы.',hydrant:'Не основной clue.',landscape:'Вулканические горы, тропики, рисовые поля.',meta:'3 blur-кластера чёрного номера + JALAN + левое движение.',confuse:'Малайзия, Филиппины, Таиланд.',last:'Indonesia vs Malaysia: номера 3 vs 2 кластера — хороший shortcut, но подтверждай архитектурой/дорожным качеством.'},
{key:'singapore',name:'Сингапур',code:'sg',region:'Азия',domain:'.sg',drive:'СЛЕВА',language:'Английский повсеместно; также китайский, малайский, тамильский.',plates:'Чёрные/белые варианты; не путай со стабильным 2/3-cluster правилом Malaysia/Indonesia.',roads:'Идеально ухоженные, широкие, зелёные; road marking HUMP AHEAD — известный clue.',roadside:'Очень чисто, много озеленения, строгая инфраструктура.',architecture:'Высотные HDB-жилые блоки, современные башни, тропическая зелень буквально между ними.',urban:'Почти всё ощущается как город; очень мало «бедной» roadside застройки.',religion:'Мечети, храмы, церкви — мультикультурно.',hydrant:'Не основной clue.',landscape:'Плоско/слегка холмисто, тропики.',meta:'Слишком чисто/богато + English + left drive + dense high-rises.',confuse:'Малайзия, Гонконг.',last:'Singapore vs Malaysia: Singapore почти всегда значительно плотнее, чище и городнее.'},
{key:'southafrica',name:'ЮАР',code:'za',region:'Африка',domain:'.za',drive:'СЛЕВА',language:'Английский + Afrikaans + местные языки. Afrikaans похож на Dutch: straat, dorp и т.п.',plates:'Белые номера, региональные варианты.',roads:'СИЛЬНЫЙ clue: жёлтые внешние линии по краям дороги на многих трассах.',roadside:'Разнообразные столбы; иногда крупные птичьи гнёзда на опорах.',architecture:'От богатых пригородов за стенами до townships; сельская застройка очень разная.',urban:'Йоханнесбург/Кейптаун современные, но не как Gulf.',religion:'Церкви чаще заметны, мечети есть регионально.',hydrant:'Не основной clue.',landscape:'От средиземноморского Cape до саванн и гор.',meta:'Yellow outer lines + left drive + English/Afrikaans.',confuse:'Ботсвана, Лесото, Эсватини, Австралия.',last:'Если южная Африка и жёлтые outer lines — сначала ЮАР/соседи, затем ландшафт.'},
{key:'ghana',name:'Гана',code:'gh',region:'Африка',domain:'.gh',drive:'справа',language:'Английский.',plates:'Светлые номера.',roads:'Тропические/пыльные дороги, городская среда Западной Африки.',roadside:'Не самый уникальный набор.',architecture:'Низкая бетонная застройка, corrugated roofs, магазины вдоль дорог.',urban:'Accra плотная и хаотичная.',religion:'Церкви и мечети обе встречаются.',hydrant:'Не основной clue.',landscape:'Тропическая зелень на юге, суше к северу.',meta:'Очень сильный Ghana car meta: чёрная лента на roof rack Google car.',confuse:'Нигерия, Уганда, Кения.',last:'Если виден roof rack с black tape — это важнее почти любого «вайба».'},
{key:'kenya',name:'Кения',code:'ke',region:'Африка',domain:'.ke',drive:'СЛЕВА',language:'Английский + суахили: barabara, shule, mjini; много English.',plates:'Задние номера часто жёлтые, передние белые — британская традиция.',roads:'Разнообразно, от Nairobi до грунтовок.',roadside:'Сильный Google-car clue: чёрный snorkel сбоку капота.',architecture:'Low-rise бетон, metal roofs; Nairobi местами высотный.',urban:'Много matatu/микроавтобусов.',religion:'Церкви и мечети в зависимости от региона.',hydrant:'Не основной clue.',landscape:'Саванна, высокогорья, тропический coast.',meta:'Snorkel — один из лучших clues.',confuse:'Уганда, ЮАР, Ботсвана.',last:'Kenya vs Uganda: Kenya snorkel; Uganda часто unique follow/car meta и жёлтые задние номера.'},
{key:'uganda',name:'Уганда',code:'ug',region:'Африка',domain:'.ug',drive:'СЛЕВА',language:'Английский широко используется.',plates:'Задние номера жёлтые.',roads:'Красно-коричневая почва часто видна вне городов.',roadside:'Coverage/car meta может быть сильнее инфраструктуры.',architecture:'Низкая бетонная/кирпичная застройка, metal roofs.',urban:'Kampala холмистая и хаотичная.',religion:'Церкви и мечети.',hydrant:'Не основной clue.',landscape:'Зелёные холмы, экваториальный климат.',meta:'Uganda unique car — сильный clue на подходящем coverage.',confuse:'Кения, Гана, Нигерия.',last:'Если East Africa + left drive: проверь snorkel (Kenya) и car meta Uganda.'},
{key:'usa',name:'США',code:'us',region:'Америка',domain:'.us (но чаще .com!)',drive:'справа',language:'Английский. Домены .com/.org НЕ дают страну; .us встречается гораздо реже.',plates:'Задний номер обязателен, передний зависит от штата. Формы/цвета сильно региональны.',roads:'Жёлтая центральная линия, белые outer lines; много word-based signs. NO PASSING ZONE pennant — сильная форма.',roadside:'Почтовые ящики, широкие обочины, деревянные poles, state-specific signs.',architecture:'Suburbs — detached houses и гаражи; strip malls; downtown высотки только в крупных городах.',urban:'Очень широкие дороги/парковки; мало пешеходной инфраструктуры в suburban areas.',religion:'Церкви часты; мечети не country clue.',hydrant:'Наземные гидранты очень обычны, но цвет НЕ стандартизирован по стране — красный/жёлтый/синий зависит от города/службы.',landscape:'Практически всё от пустынь до лесов/гор.',meta:'MUTCD signs и дорожная разметка важнее архитектуры.',confuse:'Канада, Австралия, иногда Южная Африка.',last:'US vs Canada: speed signs США часто SPEED LIMIT, Canada чаще MAXIMUM; дорожные щиты/линии и utility poles добивают.'},
{key:'canada',name:'Канада',code:'ca',region:'Америка',domain:'.ca',drive:'справа',language:'Английский, в Quebec французский. Домен .ca очень сильный.',plates:'Варьируются по провинциям; многие имеют только задний номер.',roads:'Североамериканские yellow centerlines; MAXIMUM вместо SPEED LIMIT очень полезно.',roadside:'Деревянные poles, очень широкие пространства; Quebec signage отличается.',architecture:'Североамериканская suburban архитектура; в Quebec более французский характер.',urban:'Похож на США.',religion:'Не основной clue.',hydrant:'Ньюфаундленд имеет узнаваемые fire hydrant markers как региональную мету; обычные цвета гидрантов не country-wide clue.',landscape:'Леса, озёра, горы на западе, прерии.',meta:'MAXIMUM signs + .ca + Canada-specific provincial infrastructure.',confuse:'США.',last:'Canada vs USA: ищи MAXIMUM, .ca, канадские province signs; не опирайся на гидрант.'},
{key:'spain',name:'Испания',code:'es',region:'Европа',domain:'.es',drive:'справа',language:'Испанский: calle, carretera, salida, ayuntamiento; ñ. В Каталонии carrer; в Галисии/Басконии другие языки.',plates:'Белые EU-номера.',roads:'Жёлтые guardrail reflectors — полезно; хорошие трассы, сухие обочины во многих регионах.',roadside:'Ladder poles встречаются; Spanish bollards.',architecture:'Штукатурка/камень, красная черепица; юг суше и белее, север зеленее.',urban:'Плотные apartment blocks по краям городов.',religion:'Католические церкви.',hydrant:'Не основной clue.',landscape:'Очень разнообразно, но большая часть суше Франции.',meta:'Calle/salida + Spanish infrastructure.',confuse:'Португалия, Италия, юг Франции.',last:'Spain vs Portugal: Calle vs Rua; Spanish язык без ã/õ, Portuguese часто ã/õ/ç; старые PT номера могли иметь жёлтую полосу справа.'},
{key:'portugal',name:'Португалия',code:'pt',region:'Европа',domain:'.pt',drive:'справа',language:'Португальский: rua, estrada, saída; ã, õ, ç, lh, nh. Письменно отличается от испанского довольно быстро.',plates:'Современные белые EU; старые имели заметную жёлтую полосу справа.',roads:'Очень характерны мощёные sidewalks/cobblestone; дорожная среда часто темнее/гранитнее на севере.',roadside:'Tall ladder poles; red reflector в ряде bolllards/guardrails.',architecture:'Плитка azulejo, светлая штукатурка, черепица; эвкалипты часто.',urban:'Узкие улицы, каменные/плиточные фасады.',religion:'Католические церкви.',hydrant:'Не основной clue.',landscape:'Атлантический север зеленее, юг суше.',meta:'RUA + Portuguese diacritics + cobblestone sidewalks.',confuse:'Испания.',last:'Если сомнение ES/PT — ищи RUA/CALLE и ã/õ.'},
{key:'italy',name:'Италия',code:'it',region:'Европа',domain:'.it',drive:'справа',language:'Итальянский: via, strada, comune, uscita, attenzione; много гласных, gli/chi.',plates:'Белые EU-номера часто с СИНИМИ полосами С ОБЕИХ СТОРОН.',roads:'Белые линии; guardrail endings/reflectors имеют свои паттерны.',roadside:'Trident pole tops встречаются.',architecture:'Штукатурка, shutters на окнах, черепица; много 2–5 этажных домов даже в маленьких городах.',urban:'Исторические центры очень плотные.',religion:'Католические церкви повсеместно.',hydrant:'Не основной clue.',landscape:'Альпы, Апеннины, средиземноморье.',meta:'VIA + blue bands both sides на номере — очень хороший combo.',confuse:'Испания, Хорватия, Франция.',last:'Italy vs Croatia: язык Via/Comune vs Ulica/Hrvatska; Италия чаще синие полосы номера с двух сторон.'},
{key:'poland',name:'Польша',code:'pl',region:'Европа',domain:'.pl',drive:'справа',language:'Польский: ł, ą, ę, ś, ć, ń, ź, ż; ulica/ul., droga. Ł — быстрый clue.',plates:'Белые EU-номера.',roads:'Разметка стандартная европейская.',roadside:'Holey poles, но отверстия обычно не идут до земли; встречаются двойные holey poles.',architecture:'Скатные крыши, штукатурка; новые дома яркие/современные, старые деревни плотные.',urban:'Много панельных районов и обновлённых центров.',religion:'Католические церкви очень часты.',hydrant:'Не основной clue.',landscape:'В основном равнины, горы на юге.',meta:'Ł/ą/ę + польские holey poles.',confuse:'Чехия, Словакия, Литва.',last:'Если кириллицы нет, но слово выглядит «согласные + куча диакритики», ищи ł/ą/ę.'},
{key:'romania',name:'Румыния',code:'ro',region:'Европа',domain:'.ro',drive:'справа',language:'Румынский: ă, â, î, ș, ț; strada, oraș, județ. Латинский язык среди славянских соседей.',plates:'Белые EU-номера.',roads:'Толстые roadlines встречаются; сельские дороги могут быть неровными.',roadside:'Сильный clue: толстые бетонные holey poles, отверстия часто почти до земли + белое основание.',architecture:'Смешение ярких штукатуренных домов, красных крыш, сельских заборов.',urban:'Панельные районы + хаотичная suburban застройка.',religion:'Православные церкви с куполами довольно часты.',hydrant:'Не основной clue.',landscape:'Карпаты + широкие сельхозравнины.',meta:'Holey pole all the way + white base + Romanian diacritics.',confuse:'Болгария, Венгрия, Сербия.',last:'Romania vs Bulgaria: Romanian латиница; Bulgaria кириллица. Pole shape подтверждает.'},
{key:'bulgaria',name:'Болгария',code:'bg',region:'Европа',domain:'.bg',drive:'справа',language:'Кириллица: България, улица. Буква ъ часто встречается.',plates:'Белые EU-номера.',roads:'Бледный асфальт с тёмными пятнами встречается; это слабый clue.',roadside:'Alternating pole tops, small hooks; holey poles похожи на Румынию, но часто стройнее.',architecture:'Балканская, красные крыши, штукатурка/кирпич.',urban:'Панельные районы.',religion:'Православные церкви и купола.',hydrant:'Не основной clue.',landscape:'Горы + сельхозравнины.',meta:'Кириллица + EU plate + Bulgaria-specific poles.',confuse:'Сербия, Северная Македония, Румыния.',last:'Bulgaria vs Serbia: в Сербии часто ј/љ/њ/ћ; болгарский ъ.'},
{key:'sweden',name:'Швеция',code:'se',region:'Европа',domain:'.se',drive:'справа',language:'Шведский: å ä ö; väg, gata. Часто слова с -vägen.',plates:'Белые EU-номера.',roads:'Короткие прерывистые outer lines; центральные линии обычно белые.',roadside:'Сине-жёлтые chevrons — очень сильный clue; snow poles.',architecture:'Деревянные красные дома с белыми наличниками — частый rural образ, но не везде.',urban:'Скандинавская аккуратность, средняя этажность.',religion:'Лютеранские церкви.',hydrant:'Не основной clue.',landscape:'Леса, озёра, север более пустой.',meta:'Blue+yellow chevrons + short outer dashes.',confuse:'Финляндия, Норвегия.',last:'Sweden vs Finland: Finnish слова гораздо длиннее и часто aa/ää; Finland outer lines чаще solid, Sweden short dashed.'},
{key:'finland',name:'Финляндия',code:'fi',region:'Европа',domain:'.fi',drive:'справа',language:'Финский: ä ö, много двойных гласных aa/ää/ii, очень длинные слова; tie = дорога.',plates:'Белые EU-номера.',roads:'Side lines часто сплошные; может быть жёлтая/оранжевая центральная разметка на старых покрытиях/контекстах.',roadside:'Snow poles; знаки имеют особенности относительно Sweden/Norway.',architecture:'Дерево, простые дома, много леса между поселениями.',urban:'Низкая плотность за пределами крупных городов.',religion:'Лютеранские церкви.',hydrant:'Не основной clue.',landscape:'ОЗЁРА + леса — очень часто.',meta:'Finnish long words + lakes + solid side lines.',confuse:'Швеция, Эстония.',last:'Finland vs Sweden: язык обычно решает — Finnish не похож на Scandinavian Germanic, много длинных слов с двойными гласными.'},
{key:'norway',name:'Норвегия',code:'no',region:'Европа',domain:'.no',drive:'справа',language:'Норвежский: æ ø å; vei/veg, gate.',plates:'Обычные белые; ЗЕЛЁНЫЕ номера встречаются на коммерческих машинах — не на всех.',roads:'Длинные outer lines; жёлто-оранжевая центральная линия — очень полезно для Европы.',roadside:'Bamboo snow poles, горные ограждения.',architecture:'Деревянные дома, часто тёмные/красные, очень аккуратно.',urban:'Мало больших городов; Oslo современный.',religion:'Лютеранские церкви.',hydrant:'Не основной clue.',landscape:'Фьорды, очень крутые горы, вода.',meta:'Yellow-orange centerline + dramatic landscape.',confuse:'Швеция, Исландия.',last:'Norway vs Sweden: Norway чаще жёлтый/оранжевый центр и намного драматичнее рельеф.'},
{key:'uk',name:'Великобритания',code:'gb',region:'Европа',domain:'.uk',drive:'СЛЕВА',language:'Английский. Домен .uk / .co.uk очень сильный.',plates:'Передний БЕЛЫЙ, задний ЖЁЛТЫЙ.',roads:'Левое движение; длинные centerlines, британские road markings.',roadside:'Живые изгороди, каменные стены, узкие lanes.',architecture:'Красный кирпич, terraced houses, chimney pots — очень характерно.',urban:'Плотные rows of houses, narrow streets.',religion:'Церкви с башнями/шпилями.',hydrant:'Большинство hydrant connections под землёй; жёлтые H-маркеры указывают точки — это инфраструктурный clue, но не всегда видно.',landscape:'Зелёно, холмы, hedge-lined roads.',meta:'White front/yellow rear + left drive.',confuse:'Ирландия, иногда NZ/Australia по движению.',last:'UK vs Ireland: UK задние жёлтые номера; Ireland EU white plates и жёлтые dashed outer lines.'},
{key:'ireland',name:'Ирландия',code:'ie',region:'Европа',domain:'.ie',drive:'СЛЕВА',language:'Английский + ирландский; bilingual signs, ирландские названия с необычными сочетаниями букв.',plates:'Белые EU-номера и спереди, и сзади.',roads:'Очень сильный clue: жёлтые линии по внешним краям дороги.',roadside:'Каменные стены, hedges, rounded gates.',architecture:'Светлая штукатурка, detached houses, тёмные крыши.',urban:'Невысокие города.',religion:'Католические церкви.',hydrant:'Не основной clue.',landscape:'Очень зелёно, мягкие холмы.',meta:'Left drive + yellow outer edge lines + white EU plates.',confuse:'UK.',last:'UK vs Ireland: задний номер UK жёлтый; Ireland белый. Жёлтые outer lines → Ireland.'},
{key:'australia',name:'Австралия',code:'au',region:'Океания',domain:'.au',drive:'СЛЕВА',language:'Английский, .com.au/.au.',plates:'Очень разные по штатам.',roads:'Белый центр/edge или жёлтые особенности локально; огромные расстояния.',roadside:'Australian bollard: white + red front reflector + GREY rear reflector. Turkey похож, но заднего reflector обычно нет.',architecture:'Suburban detached houses, metal roofs, широкие участки.',urban:'Крупные города современные и растянутые.',religion:'Не основной clue.',hydrant:'Цвет/тип гидранта регионален.',landscape:'Эвкалипты, сухие районы, красная почва, побережье.',meta:'Left drive + eucalyptus + AU road furniture.',confuse:'Новая Зеландия, ЮАР, Турция по bolllards.',last:'Australia vs Turkey: driving side решает сразу — AU слева, Turkey справа.'},
{key:'newzealand',name:'Новая Зеландия',code:'nz',region:'Океания',domain:'.nz',drive:'СЛЕВА',language:'Английский + Māori; .co.nz/.nz.',plates:'Белые номера.',roads:'Белые линии; NZ bollards; Give Way signage.',roadside:'Очень зелёные roadside, деревянные poles.',architecture:'Низкие detached houses, metal roofs.',urban:'Небольшие города, Auckland/Wellington крупнее.',religion:'Не основной clue.',hydrant:'Не основной clue.',landscape:'Очень зелёно, драматичные горы/овцы/пастбища.',meta:'NZ bollards + left drive + lush landscape.',confuse:'Австралия, UK.',last:'NZ vs Australia: NZ гораздо зеленее/гористее в среднем; AU чаще суше и эвкалиптовее.'}
];

const pairNotes={
 'france|germany':'Сначала язык: RUE / SORTIE / MAIRIE / é → Франция. STRASSE/STRAẞE / AUSFAHRT / ß / äöü → Германия. Без текста: немецкий bollard с большой чёрной панелью обычно проще узнать.',
 'germany|netherlands':'Нидерланды: жёлтые номера спереди и сзади + экстремально плоско + велосипеды/каналы. Германия: белые номера + немецкий язык + немецкие bollards.',
 'croatia|slovakia':'Домен .hr vs .sk. Хорватский: ć/đ/Hrvatska; словацкий: ľ/ô/ä/Slovensko. Синий fire hydrant и красный кирпич толкают в Хорватию; жирный шрифт знаков и более горный север — в Словакию.',
 'india|iran':'Первое: движение. India слева, Iran справа. Второе: India — английский + индийские письменности; Iran — персидско-арабская вязь. Домены .in / .ir.',
 'turkey|uae':'Турция: латиница с ğ/ş/ı/İ, .tr, много apartment blocks и региональных water tanks. UAE: Arabic + English, .ae, пустыня, сверхширокие дороги, light-colored stone, Dubai/Abu Dhabi high-rises.',
 'malaysia|indonesia':'Обе слева, обе используют jalan. Номер: Malaysia чаще 2 светлых blur-кластера, Indonesia 3. Malaysia обычно более ухоженная дорожная среда; Indonesia чаще плотнее/хаотичнее и мотоциклетнее.',
 'sweden|finland':'Sweden: short dashed outer lines, blue-yellow chevrons, Germanic language. Finland: очень длинные финские слова, double vowels, чаще solid outer lines, море озёр.',
 'sweden|norway':'Norway: жёлто-оранжевый центр и драматичные горы/фьорды. Sweden: центр чаще белый, short outer dashes, blue-yellow chevrons.',
 'spain|portugal':'Ищи слова: CALLE vs RUA. Portuguese: ã/õ/ç/lh/nh; Spanish: ñ. Португалия часто даёт cobblestone sidewalks.',
 'uk|ireland':'Обе слева. UK задний номер жёлтый, Ireland белые EU номера. Ireland часто жёлтые outer edge lines.',
 'czechia|slovakia':'CZ: ř/ě/ů. SK: ľ/ô/ä/ŕ/ĺ. Slovakia чаще bold road-sign font и либо очень flat, либо более резко mountainous.',
 'slovenia|croatia':'Словения чаще более альпийская/лесистая и аккуратная. Хорватия: ć/đ/Hrvatska, red-brick architecture, blue hydrants, Adriatic karst.'
};

const quickPairs=[['france','germany'],['germany','netherlands'],['croatia','slovakia'],['india','iran'],['turkey','uae'],['malaysia','indonesia'],['czechia','slovakia'],['slovenia','croatia'],['spain','portugal'],['uk','ireland'],['sweden','finland'],['sweden','norway']];

const latinTips=[
['Французский','rue, mairie, sortie, école, chemin','é è ê à ç','france'],
['Немецкий','Straße, Ausfahrt, Einbahn, Bahnhof','ß ä ö ü','germany'],
['Нидерландский','straat, weg, gemeente, ingang/uitgang','ij, aa, ee, oo','netherlands'],
['Словацкий','obec, cesta, námestie, Slovensko','ľ ô ä ŕ ĺ','slovakia'],
['Хорватский','ulica, cesta, općina, Hrvatska','č ć đ š ž','croatia'],
['Словенский','ulica, cesta, občina, Slovenije','č š ž','slovenia'],
['Польский','ulica, droga','ł ą ę ś ć ń ź ż','poland'],
['Испанский','calle, carretera, salida, ayuntamiento','ñ','spain'],
['Португальский','rua, estrada, saída','ã õ ç lh nh','portugal'],
['Итальянский','via, strada, comune, uscita','gli chi','italy'],
['Румынский','strada, oraș, județ','ă â î ș ț','romania'],
['Турецкий','cadde/caddesi, sokak, belediyesi','ğ ş ı İ ç ö ü','turkey'],
['Шведский','väg, gata','å ä ö','sweden'],
['Норвежский','vei/veg, gate','æ ø å','norway'],
['Финский','tie; очень длинные слова','ä ö + aa/ää/ii','finland']
];

const hydrants=[
{country:'croatia',title:'🇭🇷 Хорватия — синие fire hydrants',strength:'сильный/средний',text:'LearnableMeta отдельно выделяет Blue Fire Hydrants как хорватскую мету. Если видишь характерный ярко-синий наземный гидрант в балканской среде — подними Хорватию в списке кандидатов.'},
{country:'canada',title:'🇨🇦 Newfoundland — hydrant markers',strength:'региональный',text:'В Ньюфаундленде есть отдельная GeoGuessr-мета по маркерам пожарных гидрантов. Это не вся Канада и не просто цвет самого гидранта.'},
{country:'uk',title:'🇬🇧 UK — underground hydrants + H markers',strength:'слабый/подтверждение',text:'В Британии пожарные точки часто подземные; на улице можно заметить жёлтые H-marker plates. Используй только вместе с британской дорожной средой.'},
{country:'usa',title:'🇺🇸 США — наземные гидранты очень обычны',strength:'слабый',text:'Красные/жёлтые/синие гидранты часто бросаются в глаза в suburbs, но цвет зависит от города и стандарта службы. Не угадывай США по одному цвету.'}
];

function byKey(k){return C.find(x=>x.key===k)}
function pairKey(a,b){return [a,b].sort().join('|')}
function flag(c){return `https://flagcdn.com/w160/${c.code}.png`}
function clue(label,text,level=''){return `<div class="clue-row ${level}"><b>${label}</b><span>${text}</span></div>`}
function compareCard(c){return `<article class="compare-card"><div class="compare-head"><img src="${flag(c)}" alt=""><div><h3>${c.name}</h3><div class="country-tags"><span class="country-tag">${c.domain}</span><span class="country-tag">${c.drive}</span><span class="country-tag">${c.region}</span></div></div></div><div class="compare-body">${clue('Язык',c.language,'strong')}${clue('Номера',c.plates)}${clue('Дороги',c.roads)}${clue('Столбы / roadside',c.roadside)}${clue('Архитектура',c.architecture,'weak')}${clue('Город',c.urban,'weak')}${clue('Религия / объекты',c.religion,'weak')}${clue('Гидранты',c.hydrant,'weak')}${clue('Ландшафт',c.landscape,'weak')}${clue('Meta',c.meta,'strong')}<div class="decision"><b>Последняя проверка:</b> ${c.last}</div></div></article>`}
function renderCompare(){const a=byKey(document.getElementById('compareA').value),b=byKey(document.getElementById('compareB').value);document.getElementById('countryCompare').innerHTML=compareCard(a)+compareCard(b);document.getElementById('pairDecision').innerHTML=`<b>Решающий порядок:</b> ${pairNotes[pairKey(a.key,b.key)]||`1) язык/домен → 2) сторона движения/номер → 3) bolllards/roadlines → 4) только потом архитектура и ландшафт. ${a.name}: ${a.last} ${b.name}: ${b.last}`}`}

const selA=document.getElementById('compareA'),selB=document.getElementById('compareB');
C.forEach(c=>{selA.add(new Option(c.name,c.key));selB.add(new Option(c.name,c.key))});selA.value='france';selB.value='germany';renderCompare();
selA.onchange=renderCompare;selB.onchange=renderCompare;document.getElementById('swapCountries').onclick=()=>{const t=selA.value;selA.value=selB.value;selB.value=t;renderCompare()};

function countryMini(c){return `<article class="country-card" data-search="${[c.name,c.domain,c.language,c.plates,c.roads,c.roadside,c.architecture,c.urban,c.religion,c.hydrant,c.landscape,c.meta,c.confuse].join(' ').toLowerCase()}"><div class="country-head"><img src="${flag(c)}" alt=""><div><h3>${c.name}</h3><div class="country-tags"><span class="country-tag">${c.domain}</span><span class="country-tag">${c.drive}</span></div></div></div><div class="country-body"><div class="clue-rank"><div class="clue-line"><span class="rank">1</span><span><b>Язык:</b> ${c.language}</span></div><div class="clue-line"><span class="rank">2</span><span><b>Номера/дороги:</b> ${c.plates} ${c.roads}</span></div><div class="clue-line"><span class="rank">3</span><span><b>Roadside:</b> ${c.roadside}</span></div><div class="clue-line"><span class="rank">4</span><span><b>Архитектура:</b> ${c.architecture}</span></div><div class="clue-line"><span class="rank">5</span><span><b>Meta:</b> ${c.meta}</span></div></div><details><summary>Ещё детали</summary>${clue('Город',c.urban)}${clue('Религия / мечети / храмы',c.religion)}${clue('Гидранты',c.hydrant)}${clue('Ландшафт',c.landscape)}${clue('Чаще путается',c.confuse)}<div class="decision">${c.last}</div></details><button class="compare-btn" data-compare="${c.key}">Сравнить эту страну</button></div></article>`}
function renderCountries(){const q=document.getElementById('countrySearch').value.trim().toLowerCase(),r=document.getElementById('countryRegion').value;document.getElementById('countryGrid').innerHTML=C.filter(c=>(r==='all'||c.region===r)&&(!q||[c.name,c.domain,c.language,c.plates,c.roads,c.roadside,c.architecture,c.urban,c.religion,c.hydrant,c.landscape,c.meta,c.confuse].join(' ').toLowerCase().includes(q))).map(countryMini).join('')}
document.getElementById('countrySearch').oninput=renderCountries;document.getElementById('countryRegion').onchange=renderCountries;renderCountries();

document.addEventListener('click',e=>{const b=e.target.closest('[data-compare]');if(!b)return;selA.value=b.dataset.compare;document.getElementById('compare').scrollIntoView({behavior:'smooth'});renderCompare()});

document.getElementById('pairGrid').innerHTML=quickPairs.map(([a,b])=>{const A=byKey(a),B=byKey(b);return `<article class="country-card"><div class="country-head"><img src="${flag(A)}"><img src="${flag(B)}"><div><h3>${A.name} ↔ ${B.name}</h3></div></div><div class="country-body"><p>${pairNotes[pairKey(a,b)]}</p><button class="compare-btn pair-btn" data-a="${a}" data-b="${b}">Открыть сравнение</button></div></article>`}).join('');
document.querySelectorAll('.pair-btn').forEach(b=>b.onclick=()=>{selA.value=b.dataset.a;selB.value=b.dataset.b;renderCompare();document.getElementById('compare').scrollIntoView({behavior:'smooth'})});

const domains=[...C].sort((a,b)=>a.domain.localeCompare(b.domain));document.getElementById('domainGrid').innerHTML=domains.map(c=>`<button class="domain-card" data-compare="${c.key}"><b>${c.domain}</b><img src="${flag(c)}" alt=""><span>${c.name}</span></button>`).join('');

document.getElementById('hydrantGrid').innerHTML=hydrants.map(h=>`<article class="country-card"><div class="country-body"><div class="country-tags"><span class="country-tag">${h.strength}</span></div><h3>${h.title}</h3><p>${h.text}</p><button class="compare-btn" data-compare="${h.country}">Открыть страну</button></div></article>`).join('');

document.getElementById('latinGrid').innerHTML=latinTips.map(([name,words,letters,key])=>`<article class="country-card"><div class="country-body"><h3>${name}</h3><div class="language-sample">${letters}</div><p><b>Слова:</b> ${words}</p><button class="compare-btn" data-compare="${key}">Страна →</button></div></article>`).join('');