/* Photo-first catalogue. Source links point to the individual learning examples. */
(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).toLocaleLowerCase('ru').normalize('NFD').replace(/\p{M}/gu,'').replace(/ё/g,'е').replace(/[-–—]/g,' ');
const names=new Intl.DisplayNames(['ru'],{type:'region'}), country=c=>({'US':'США','KR':'Южная Корея','UM':'Мидуэй'}[c]||names.of(c)||c);
const flag=c=>c.length===2?[...c].map(l=>String.fromCodePoint(l.charCodeAt(0)+127397)).join(''):'';
let data,items,categories,profiles,byId,allCountries,selected=new Set(),galleries=[],known=new Set();
try{known=new Set(JSON.parse(localStorage.getItem('geo-photo-known-v1')||'[]'));}catch{}
const save=()=>{try{localStorage.setItem('geo-photo-known-v1',JSON.stringify([...known]));}catch{}};
function photo(x,{large=false,blind=false,eager=false}={}){
 const alt=blind?'Учебная фотография без ответа':x.title+' · '+country(x.country);
 if(x.photo&&!large){const p=x.photo;return `<span class="va-photo va-sprite"><img loading="${eager?'eager':'lazy'}" src="${esc(p.atlas)}" alt="${esc(alt)}" style="width:${p.cols*100}%;height:${p.rows*100}%;left:-${p.x*100}%;top:-${p.y*100}%;" data-original="${esc(x.image)}"></span>`;}
 return `<span class="va-photo${large?' va-large':''}"><img loading="${eager||large?'eager':'lazy'}" src="${esc(x.image)}" alt="${esc(alt)}"></span>`;
}
function attachErrors(root){root.querySelectorAll('.va-photo img').forEach(img=>img.addEventListener('error',()=>{
 const p=img.parentElement;
 if(img.dataset.original){img.src=img.dataset.original;delete img.dataset.original;img.removeAttribute('style');p.classList.remove('va-sprite');return;}
 p.classList.add('va-failed');if(!p.querySelector('.va-retry')){const b=document.createElement('button');b.type='button';b.className='va-retry';b.textContent='Повторить загрузку фото';b.onclick=e=>{e.stopPropagation();p.classList.remove('va-failed');b.remove();const url=img.src;img.removeAttribute('src');img.src=url;};p.append(b);}
 }));}
const opts=(codes=allCountries)=>codes.map(c=>`<option value="${c}">${esc(country(c))}</option>`).join('');
const catOpts=allowed=>allowed.map(c=>`<option value="${c}">${esc(categories[c])}</option>`).join('');
const badge=x=>x.scope==='regional'?'Регион':x.scope==='shared'?'Есть похожие':'Пример';
function card(x,eager=false){return `<article class="va-card"><button type="button" class="va-open" data-photo="${x.id}" aria-label="Увеличить: ${esc(x.title)}">${photo(x,{eager})}<span class="va-zoom" aria-hidden="true">↗</span></button><button class="va-pick${selected.has(x.id)?' active':''}" data-pick="${x.id}" aria-label="Сравнить: ${esc(x.title)}" aria-pressed="${selected.has(x.id)}">${selected.has(x.id)?'✓':'+'}</button><div class="va-caption"><button class="va-country" data-visual-country="${x.country}">${flag(x.country)} ${esc(country(x.country))}</button><h4>${esc(x.title)}</h4><small>${esc(x.region||badge(x))}</small></div></article>`;}
const searchTokens=s=>norm(s).split(/\s+/).filter(Boolean).map(t=>t.length>3?t.replace(/(ыми|ими|ого|его|ая|яя|ое|ее|ые|ие|ый|ий|ой|ых|их|ами|ями|ов|ев|ам|ям|ы|и|а|я|у|ю|е|о)$/u,''):t);
function gallery(host,allowed,{global=false}={}){
 host.className='va-catalog';const codes=allCountries.filter(c=>items.some(x=>x.country===c&&allowed.includes(x.category)));
 host.innerHTML=`<div class="va-tools"><label class="va-search-label">Найти деталь<input class="va-search" type="search" placeholder="Красная кайма, отверстия, белый номер…"></label><label>Страна<select class="va-country-filter"><option value="all">Все страны</option>${opts(codes)}</select></label><label>Тип<select class="va-category-filter"><option value="all">Все типы</option>${catOpts(allowed)}</select></label>${global?'<label>Регион<select class="va-region-filter"><option value="all">Весь мир</option><option value="America">Америка</option><option value="Europe">Европа</option><option value="Asia">Азия</option><option value="Africa">Африка</option><option value="Oceania">Океания</option></select></label>':''}<button type="button" class="va-reset">Сбросить</button></div><div class="va-gallery-meta"><span class="va-count" role="status"></span><button type="button" class="va-start">Учить эти фото →</button></div><div class="va-grid"></div><div class="va-more-row"><button class="va-more" type="button">Ещё 36 фото</button><button class="va-all" type="button">Показать всё</button></div>`;
 let limit=36,filtered=[];
 const filter=()=>{const q=norm($('.va-search',host).value),c=$('.va-country-filter',host).value,cat=$('.va-category-filter',host).value,region=$('.va-region-filter',host)?.value||'all';filtered=items.filter(x=>allowed.includes(x.category)&&(c==='all'||x.country===c)&&(cat==='all'||x.category===cat)&&(region==='all'||(region==='America'?/America/.test(x.worldRegion):x.worldRegion===region))&&searchTokens(q).every(t=>searchTokens([x.title,country(x.country),x.country,x.region,categories[x.category],x.note,profiles.find(p=>p.code===x.country)?.englishName].join(' ')).some(w=>w.includes(t))));};
 const render=()=>{filter();const visible=filtered.slice(0,limit);$('.va-count',host).textContent=`${filtered.length} фото · показано ${visible.length}`;$('.va-grid',host).innerHTML=visible.map(x=>card(x,limit===Infinity)).join('')||'<p class="va-empty">По этим фильтрам фотографий нет. Сбрось фильтры или выбери другую страну.</p>';$('.va-more-row',host).hidden=filtered.length<=limit;$('.va-start',host).disabled=!filtered.length;attachErrors(host);};
 const ref={host,render,filterCountry(c){$('.va-country-filter',host).value=codes.includes(c)?c:'all';$('.va-category-filter',host).value='all';$('.va-search',host).value='';if($('.va-region-filter',host))$('.va-region-filter',host).value='all';limit=36;render();},setCategory(c){$('.va-category-filter',host).value=c;limit=36;render();}};
 host.addEventListener('input',e=>{if(e.target.matches('.va-search')){limit=36;render();}});
 host.addEventListener('change',()=>{limit=36;render();});
 $('.va-more',host).onclick=()=>{limit+=36;render();};$('.va-all',host).onclick=()=>{limit=Infinity;render();};
 $('.va-reset',host).onclick=()=>{host.querySelectorAll('select').forEach(s=>s.value='all');$('.va-search',host).value='';limit=36;render();};
 $('.va-start',host).onclick=()=>{startTraining(filtered.map(x=>x.id));};
 galleries.push(ref);render();return ref;
}
function details(x){const similar=x.similar.filter(c=>c!==x.country);return `<div class="va-detail-text"><span class="va-kind">${esc(x.region||badge(x))}</span><h3>${flag(x.country)} ${esc(country(x.country))}</h3><h4>${esc(x.title)}</h4>${x.note?`<p>${esc(x.note)}</p>`:''}${similar.length?`<p class="va-similar">Похожие признаки: ${similar.map(c=>`<button data-visual-country="${c}">${esc(country(c))}</button>`).join(' · ')}</p>`:'<p class="va-similar">Фото показывает один вариант. Подтверди страну вторым признаком.</p>'}<div class="va-detail-actions"><button data-visual-country="${x.country}">Все фото страны</button><button data-learn-one="${x.id}">Учить этот пример</button><a href="${esc(x.source)}" target="_blank" rel="noopener">Источник: ${esc(x.provider||'GeoMetas')} ↗</a>${x.factSource?`<a href="${esc(x.factSource)}" target="_blank" rel="noopener">Уточнение формата номера: официальный источник ↗</a>`:''}</div></div>`;}
function openDialog(content){const dialog=$('#vaDialog');$('.va-dialog-body',dialog).innerHTML=content;attachErrors(dialog);if(!dialog.open)dialog.showModal();}
function openPhoto(x){openDialog(`<div class="va-detail">${photo(x,{large:true})}${details(x)}</div>`);}
function updateCompare(){const tray=$('#vaCompare');tray.hidden=!selected.size;$('.va-compare-count',tray).textContent=`Для сравнения: ${selected.size} / 4`;galleries.forEach(g=>g.host.querySelectorAll('[data-pick]').forEach(b=>{const yes=selected.has(b.dataset.pick);b.textContent=yes?'✓':'+';b.classList.toggle('active',yes);b.setAttribute('aria-pressed',yes);}));}
function compare(){const cards=[...selected].map(id=>byId.get(id));openDialog(`<h3>Сравни детали рядом</h3><div class="va-compare-grid">${cards.map(x=>`<article>${photo(x,{large:true})}${details(x)}</article>`).join('')}</div>`);}
let studyRows=[],studyIndex=0,revealed=false,trainingIds=null;
function bundle(c){const examples=items.filter(x=>x.country===c),used=new Set(),chosen=[];for(const x of examples){if(!used.has(x.category)){chosen.push(x);used.add(x.category);}if(chosen.length===4)break;}return chosen;}
function rebuildStudy(){const mode=$('#photoStudyMode').value,c=$('#photoStudyCountry').value,cat=$('#photoStudyCategory').value,review=$('#photoStudyReview').value;let list=trainingIds?trainingIds.map(id=>byId.get(id)):items;list=list.filter(x=>x&&(c==='all'||x.country===c)&&(cat==='all'||x.category===cat));studyRows=mode==='bundle'?[...new Set(list.map(x=>x.country))].map(c=>({id:'bundle-'+c,country:c,bundle:bundle(c)})):list;studyRows=studyRows.filter(x=>review==='all'||!known.has(x.id));studyIndex=0;renderStudy();}
function renderStudy(){const x=studyRows[studyIndex];revealed=false;$('#photoStudyAnswer').hidden=true;$('#photoStudyAnswer').innerHTML='';$('#photoStudyReveal').hidden=!x;$('#photoStudyKnow').disabled=true;$('#photoStudyAgain').disabled=true;$('#photoStudyPrev').disabled=!x;$('#photoStudyNext').disabled=!x;$('#photoStudyProgress').textContent=`${studyRows.length?studyIndex+1:0} / ${studyRows.length} · выучено ${known.size}`;$('#photoStudyQuestion').textContent=x?(x.bundle?(x.bundle.length>1?'Определи страну по сочетанию фотографий':'Где встречается этот визуальный вариант?'):'Где встречается этот визуальный вариант?'):'Колода пуста — поменяй фильтры.';$('#photoStudyImage').className=x?.bundle?'va-study-bundle':'va-study-single';$('#photoStudyImage').innerHTML=x?(x.bundle?x.bundle.map(y=>photo(y,{blind:true,eager:true})).join(''):photo(x,{blind:true,eager:true})):'';attachErrors($('#photoStudyImage'));}
function startTraining(ids,c){trainingIds=ids||null;$('#photoStudyMode').value='single';$('#photoStudyCountry').value=c||'all';$('#photoStudyCategory').value='all';$('#photoStudyReview').value='all';$('#photoStudySelection').hidden=!ids;$('#photoStudySelection').textContent=ids?`Выбрано ${ids.length} фото из каталога · показать полную колоду`:'';rebuildStudy();$('#photo-study').scrollIntoView({behavior:'smooth'});}
function studyUI(){const sec=document.createElement('section');sec.className='section va-section';sec.id='photo-study';sec.innerHTML=`<div class="section-head"><div><span class="eyebrow">УЧИТЬ ГЛАЗАМИ</span><h2>Карточки с фотографиями</h2><p>Посмотри → назови страну или варианты → открой ответ.</p></div></div><div class="va-tools"><label>Колода<select id="photoStudyMode"><option value="single">Один визуальный признак</option><option value="bundle">Связки для страны</option></select></label><label>Страна<select id="photoStudyCountry"><option value="all">Все страны</option>${opts()}</select></label><label>Категория<select id="photoStudyCategory"><option value="all">Все категории</option>${catOpts(Object.keys(categories))}</select></label><label>Повторение<select id="photoStudyReview"><option value="all">Все карточки</option><option value="review">Ещё не выученные</option></select></label><button id="photoStudyShuffle" type="button">Перемешать</button></div><button id="photoStudySelection" hidden type="button"></button><div class="va-study"><div id="photoStudyProgress" role="status"></div><h3 id="photoStudyQuestion"></h3><div id="photoStudyImage"></div><button id="photoStudyReveal" class="va-primary" type="button">Показать ответ</button><div id="photoStudyAnswer" hidden></div><div class="va-study-actions"><button id="photoStudyPrev" type="button">←</button><button id="photoStudyAgain" type="button" disabled>Повторить</button><button id="photoStudyKnow" type="button" disabled>Знаю ✓</button><button id="photoStudyNext" type="button">→</button></div></div>`;document.querySelector('main').append(sec);
 ['photoStudyMode','photoStudyCountry','photoStudyCategory','photoStudyReview'].forEach(id=>$('#'+id).onchange=()=>{trainingIds=null;$('#photoStudySelection').hidden=true;rebuildStudy();});
 $('#photoStudySelection').onclick=()=>{trainingIds=null;$('#photoStudySelection').hidden=true;rebuildStudy();};
 $('#photoStudyReveal').onclick=()=>{const x=studyRows[studyIndex];if(!x)return;revealed=true;const p=profiles.find(p=>p.code===x.country);$('#photoStudyAnswer').innerHTML=x.bundle?`<h3>${flag(x.country)} ${esc(country(x.country))}</h3><div class="va-bundle-facts">${x.bundle.map(y=>`<p><b>${esc(categories[y.category])}:</b> ${esc(y.title)}</p>`).join('')}</div>${p?`<p><b>Проверка связки:</b> ${esc(p.strong)}</p><p class="va-similar">${esc(p.confusions)}</p>`:''}<button data-visual-country="${x.country}">Все фотографии страны →</button>`:details(x);$('#photoStudyAnswer').hidden=false;$('#photoStudyReveal').hidden=true;$('#photoStudyKnow').disabled=false;$('#photoStudyAgain').disabled=false;};
 const advance=()=>{if(!studyRows.length)return;studyIndex=(studyIndex+1)%studyRows.length;renderStudy();};$('#photoStudyNext').onclick=advance;$('#photoStudyPrev').onclick=()=>{if(studyRows.length){studyIndex=(studyIndex-1+studyRows.length)%studyRows.length;renderStudy();}};
 $('#photoStudyKnow').onclick=()=>{if(!revealed)return;known.add(studyRows[studyIndex].id);save();if($('#photoStudyReview').value==='review'){studyRows.splice(studyIndex,1);studyIndex=studyRows.length?studyIndex%studyRows.length:0;renderStudy();}else advance();};
 $('#photoStudyAgain').onclick=()=>{if(!revealed)return;known.delete(studyRows[studyIndex].id);save();advance();};
 $('#photoStudyShuffle').onclick=()=>{for(let i=studyRows.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[studyRows[i],studyRows[j]]=[studyRows[j],studyRows[i]];}studyIndex=0;renderStudy();};rebuildStudy();
}
async function init(){if($('#visual-atlas'))return;try{
 const results=await Promise.all([fetch('./visual-data.json?v=20261003-visual2'),fetch('./learning-data.json?v=20261002-learning1')]);if(results.some(r=>!r.ok))throw Error('Фотоатлас: данные недоступны');[data,{countries:profiles}]=await Promise.all(results.map(r=>r.json()));items=data.items;categories=data.categories;items.forEach(x=>x.worldRegion=profiles.find(p=>p.code===x.country)?.region||'');byId=new Map(items.map(x=>[x.id,x]));allCountries=[...new Set(items.map(x=>x.country))].sort((a,b)=>country(a).localeCompare(country(b),'ru'));
 const section=document.createElement('section');section.id='visual-atlas';section.className='section va-section';section.innerHTML=`<div class="section-head"><div><span class="eyebrow">ФОТОАТЛАС · ${items.length} ПРИМЕРА</span><h2>Найди то, что увидел в игре</h2><p>${allCountries.length} стран и территорий · ${Object.keys(categories).length} тем. Нажми фото для увеличения, «+» — для сравнения.</p></div><a class="va-study-link" href="#photo-study">Учить по фото →</a></div><div class="va-category-tabs">${Object.entries(categories).map(([id,label])=>`<button data-category="${id}" type="button">${esc(label)} <small>${items.filter(x=>x.category===id).length}</small></button>`).join('')}</div><div class="va-america-chips"><span>Быстрый выбор:</span>${['US','CA','MX','BR','PE','EC','CH'].map(c=>`<button data-visual-country="${c}">${flag(c)} ${esc(country(c))}</button>`).join('')}</div><div id="visualCatalog"></div><details class="va-sources"><summary>Источники и границы подсказок</summary><p>Каталог GeoMetas: все ${data.geometasCount||563} доступных примера, дополненные ${items.length-(data.geometasCount||563)} проверенными фотографиями Plonk It. В исходных материалах указаны Plonk It и The Digital Labyrinth. Страновые связки сверяются со справочником Plonk It и OpenGuessr Education. Ссылка на отдельный пример — в увеличенном фото.</p><p>Фотография показывает вариант из конкретного покрытия. Похожие страны перечислены отдельно; их список не исчерпывающий. Машины, номера и съёмка меняются. Для природы и отсутствия детали всегда нужен второй признак.</p><a href="https://geometas.com/" target="_blank" rel="noopener">GeoMetas ↗</a> · <a href="https://education.openguessr.com/countries/learn" target="_blank" rel="noopener">OpenGuessr Education ↗</a> · <a href="https://www.plonkit.net/guide" target="_blank" rel="noopener">Plonk It ↗</a></details>`;
 $('.hero').insertAdjacentElement('afterend',section);const mainGallery=gallery($('#visualCatalog'),Object.keys(categories),{global:true});
 section.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{section.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x===b));mainGallery.setCategory(b.dataset.category);});
 const signs=$('#signs');if(signs){$('.section-head h2',signs).textContent='Знаки, стойки и шевроны — сравни по фото';$('.section-head p',signs).textContent='Кайма, фон, стрелка, обратная сторона и крепление. Один цвет встречается в нескольких странах.';gallery($('#signGrid'),['street_sign','signposts','chevrons']);}
 const poles=$('#poles');if(poles){poles.querySelectorAll(':scope > :not(.section-head)').forEach(x=>x.remove());$('.section-head h2',poles).textContent='Опоры, придорожные столбики и километровые маркеры';const host=document.createElement('div');poles.append(host);gallery(host,['poles','bollards','milestones']);}
 for(const [id,allowed,label] of [['plates',['license_plate'],'Номера в реальных панорамах'],['road-lines',['street_markings','guardrails'],'Разметка и ограждения: фотографии'],['cars',['google_car'],'Машины Google: варианты покрытия'],['environment',['flora','buildings','cars','other'],'Природа, дома и транспорт: фотографии'],['languages',['language','street_name'],'Язык на вывесках и указателях']]){const parent=$('#'+id);if(!parent)continue;const h=document.createElement('h3');h.className='subhead';h.textContent=label;const host=document.createElement('div');h.classList.add('va-section-label');$('.section-head',parent).insertAdjacentElement('afterend',h);h.insertAdjacentElement('afterend',host);gallery(host,allowed);}
 const dialog=document.createElement('dialog');dialog.id='vaDialog';dialog.className='va-dialog';dialog.innerHTML='<form method="dialog" class="va-dialog-close"><button aria-label="Закрыть" autofocus>×</button></form><div class="va-dialog-body"></div>';document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
 const tray=document.createElement('aside');tray.id='vaCompare';tray.hidden=true;tray.innerHTML='<span class="va-compare-count"></span><button class="va-compare-go" type="button">Сравнить фото</button><button class="va-compare-clear" type="button" aria-label="Очистить сравнение">×</button>';document.body.append(tray);$('.va-compare-go',tray).onclick=compare;$('.va-compare-clear',tray).onclick=()=>{selected.clear();updateCompare();};
 studyUI();const nav=$('.nav');for(const [id,label] of [['visual-atlas','Фотоатлас'],['photo-study','Учить по фото']]){const a=document.createElement('a');a.href='#'+id;a.textContent=label;nav?.prepend(a);}
 document.addEventListener('click',e=>{const p=e.target.closest('[data-photo]'),pick=e.target.closest('[data-pick]'),c=e.target.closest('[data-visual-country]'),one=e.target.closest('[data-learn-one]');if(p){openPhoto(byId.get(p.dataset.photo));}if(pick){const id=pick.dataset.pick;if(selected.has(id))selected.delete(id);else if(selected.size<4)selected.add(id);else{compare();return;}updateCompare();}if(c){dialog.close();if(allCountries.includes(c.dataset.visualCountry)){mainGallery.filterCountry(c.dataset.visualCountry);}else{mainGallery.filterCountry('all');$('.va-search',mainGallery.host).value=country(c.dataset.visualCountry);mainGallery.render();}section.scrollIntoView({behavior:'smooth'});}if(one){dialog.close();startTraining([one.dataset.learnOne]);}});
 const linkFinder=()=>{const f=$('#decision-path');if(f&&!$('.va-finder-link',f)){const a=document.createElement('a');a.href='#visual-atlas';a.className='va-finder-link';a.textContent='Определить по фотографии: знаки, номера, опоры →';$('.section-head',f)?.insertAdjacentElement('afterend',a);}document.querySelectorAll('.learn-sign-reference').forEach(x=>x.remove());};linkFinder();document.addEventListener('learningready',linkFinder);
 if(location.hash==='#visual-atlas'||location.hash==='#photo-study')$(location.hash)?.scrollIntoView();
 }catch(e){console.error('Фотоатлас',e);const notice=document.createElement('p');notice.className='va-empty';notice.textContent='Не удалось загрузить фотоатлас. Обнови страницу.';$('.hero')?.append(notice);}}
 if(document.readyState==='complete')setTimeout(init,100);else window.addEventListener('load',()=>setTimeout(init,4100),{once:true});
})();
